# Generated by Django 3.0.7 on 2020-06-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bname', models.CharField(max_length=100)),
                ('Bhouse', models.CharField(max_length=50)),
                ('Bpic', models.FileField(upload_to='')),
                ('Bclass', models.CharField(max_length=10)),
                ('Bcount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GCand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gname', models.CharField(max_length=100)),
                ('Ghouse', models.CharField(max_length=50)),
                ('Gpic', models.FileField(upload_to='')),
                ('Gclass', models.CharField(max_length=10)),
                ('Gcount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vname', models.CharField(max_length=100)),
                ('Votedone', models.BooleanField()),
                ('AdmisNo', models.IntegerField()),
                ('Vhouse', models.CharField(max_length=100)),
                ('Vdob', models.DateField()),
                ('Vclass', models.CharField(max_length=10)),
                ('BCand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebApp.BCand')),
                ('GCand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebApp.GCand')),
            ],
        ),
    ]
