# Generated by Django 3.0.7 on 2020-06-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='BCand',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='WebApp.BCand'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='GCand',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='WebApp.GCand'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='Votedone',
            field=models.BooleanField(default=False),
        ),
    ]
