# Generated by Django 3.0.7 on 2020-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20200611_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='BCand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voter',
            name='GCand',
            field=models.IntegerField(default=0),
        ),
    ]
