# Generated by Django 3.0.7 on 2020-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20200611_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcand',
            name='Bpic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gcand',
            name='Gpic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
